# These are supported funding model platforms

custom: [
'https://www.blockchain.com/btc/address/1HBPEwFccDGUw4pYDNxGsrMVTJZ9hWbbpK',
'https://etherscan.io/address/0xdCB16FDf452994E8778D0713b96A1E02Bfb5728a'
]
